name: rust_intro/d3_tricks_mod

on:
    push:
    branches: [ main ]
    pull_request:
    branches: [ main ]

env:
    CARGO_TERM_COLOR: always

defaults:
    run:
    working-directory: ./rust_intro/d3_tricks_mod

jobs:
    build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
        run: cargo build --verbose
    - name: Build Release
        run: cargo build --release --verbose
    - name: Run tests
        run: cargo test --verbose
